[project]
name = "secrets2vault"
version = "0.1.0"
authors = [{ name = "Fredrik Broman", email = "fredrik.broman@gmail.com" }]
description = "Imports Kubernetes secrets into Vault"
readme = "README.md"
license = "Unlicense"
requires-python = ">=3.13"
dependencies = ["hvac>=2.3.0"]
